# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='course',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'Unknown'), (10, 'Customer'), (30, 'Loan Officer'), (40, 'Admin')], default=0),
        ),
    ]
