# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20161026_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Account'), (2, 'Customer'), (3, 'Admin'), (4, 'Loanofficer'), (8, 'Customer Details'), (9, 'Message')], default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='level',
            field=models.CharField(choices=[('Ksh: 1,000,000', 'Ksh: 1,000,000'), ('Ksh: 500,000', 'Ksh: 500,000'), ('Ksh: 100,000', 'Ksh: 100,000'), ('Ksh: 50,000', 'Ksh: 50,000'), ('Ksh: 20,000', 'Ksh: 20,000'), ('Ksh: 10,000', 'Ksh: 10,000'), ('Ksh: 5,000', 'Ksh: 5,000'), ('Other', 'Other')], max_length=15),
        ),
    ]
